export type Industry = {
  slug: string; label: string; eyebrow: string; headline: string; intro: string;
  moment: string; name: string; message: string; reply: string; outcome: string;
  pain: string; workflow: string[]; useCases: string[]; guardrail: string;
};

export const industries: Industry[] = [
  { slug:"med-spas", label:"Med spas", eyebrow:"From treatment curiosity to booked consultation", headline:"The glow-up starts before they ever walk in.", intro:"Respond to treatment inquiries in seconds, answer the questions that stall bookings, and guide qualified prospects into your calendar.", moment:"New treatment inquiry · 8:43 PM", name:"Alyssa", message:"Do you offer lip filler consultations after work?", reply:"Absolutely. I can help you find an evening consultation and answer a few quick questions first.", outcome:"Consultation booked · Tue 6:15 PM", pain:"You paid to earn the click. Zeem protects that investment after the form is submitted.", workflow:["Answer every treatment inquiry","Qualify interest and timing","Book the consultation","Recover undecided prospects"], useCases:["Treatment FAQs","Consultation booking","No-show reminders","Old-lead reactivation"], guardrail:"Your agent handles approved information and booking—not clinical recommendations." },
  { slug:"restoration", label:"Restoration", eyebrow:"Emergency intake without the voicemail gap", headline:"When water is rising, the first calm answer wins.", intro:"Capture loss details, location, urgency, and insurance information the moment a homeowner calls—then alert the right person immediately.", moment:"Urgent water loss · 2:17 AM", name:"Marcus", message:"A pipe burst and water is spreading into the hallway.", reply:"I’m going to help route this now. Is the water source shut off, and is everyone safely away from electrical hazards?", outcome:"Emergency dispatch alerted", pain:"The after-hours call your competitor misses can become your next insurance job.", workflow:["Answer immediately","Capture loss and safety details","Trigger the on-call path","Follow up on estimates"], useCases:["Water-loss intake","Emergency escalation","Insurance capture","Estimate follow-up"], guardrail:"Safety scripts and escalation rules are approved by your team before launch." },
  { slug:"home-care", label:"Senior home care", eyebrow:"A reassuring first response for every family", headline:"Families should feel cared for from the first call.", intro:"Handle new care inquiries with patience, collect essential non-clinical details, and arrange the next conversation with your care team.", moment:"Family care inquiry · 7:06 PM", name:"Denise", message:"My father is being discharged Friday and needs help at home.", reply:"I can help your family take the next step. May I ask where he lives and when you would like care to begin?", outcome:"Care assessment requested", pain:"A thoughtful first response keeps an urgent family inquiry from becoming a call to the next agency.", workflow:["Reassure the family","Collect non-clinical needs","Confirm service area and timing","Book a care assessment"], useCases:["Family inquiries","Discharge referrals","Assessment booking","Long-term nurture"], guardrail:"The agent never provides medical advice and routes sensitive concerns to a person." },
  { slug:"law-firms", label:"Law firms", eyebrow:"Professional intake for moments that cannot wait", headline:"A potential case deserves more than voicemail.", intro:"Capture preliminary details, route urgent matters, and book consultations—without giving legal advice or replacing attorney judgment.", moment:"Potential client · 6:32 PM", name:"Jordan", message:"I was injured last week and need to know if I have a case.", reply:"I can collect preliminary details and arrange a consultation. This conversation is not legal advice.", outcome:"Consultation booked · Wed 10:00 AM", pain:"Consistent intake and persistent follow-up help protect valuable matters from slipping between calls.", workflow:["Identify the matter type","Capture approved intake fields","Route urgent or conflicting matters","Book the consultation"], useCases:["New-matter intake","Consultation scheduling","Document reminders","Unconverted-lead follow-up"], guardrail:"Clear disclosures, conflict-aware routing, and no legal advice are built into the workflow." },
  { slug:"hvac-plumbing", label:"HVAC & plumbing", eyebrow:"Booked jobs while your technicians stay on the tools", headline:"The homeowner with a problem is calling someone now.", intro:"Answer while your crew is driving, diagnosing, or under a sink. Qualify the issue, confirm the service area, and book or escalate the job.", moment:"No-cooling call · 5:51 PM", name:"Priya", message:"Our AC stopped working and the house is getting hot.", reply:"I can check the next available visit. What ZIP code are you in, and is the system completely off?", outcome:"Service window booked · 7–9 PM", pain:"Immediate response helps you win urgent work before the homeowner reaches the next listing.", workflow:["Identify the problem","Check location and urgency","Book or dispatch","Follow up on open estimates"], useCases:["Emergency calls","Service booking","Maintenance plans","Estimate recovery"], guardrail:"True emergencies and safety issues follow your approved escalation path." },
];
export const getIndustry = (slug:string) => industries.find(i => i.slug === slug);
