"use client";
import { FormEvent, useState } from "react";
import { industries } from "../lib/industries";

export function IntakeForm({defaultIndustry=""}:{defaultIndustry?:string}){
  const [status,setStatus]=useState<"idle"|"sending"|"success"|"error">("idle");
  async function submit(e:FormEvent<HTMLFormElement>){ e.preventDefault(); setStatus("sending"); const form=e.currentTarget; const data=Object.fromEntries(new FormData(form)); try{ const r=await fetch("/api/leads",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(data)}); if(!r.ok) throw new Error(); setStatus("success"); form.reset(); }catch{setStatus("error");}}
  if(status==="success") return <div className="form-success" role="status"><span>✓</span><p className="kicker">REQUEST RECEIVED</p><h3>Your custom demo is now in motion.</h3><p>We’ll review your business and prepare the strongest lead-response workflow for your situation.</p></div>;
  return <form className="intake" onSubmit={submit}><input className="hp" name="companyFax" tabIndex={-1} autoComplete="off" aria-hidden="true"/><div className="field full"><label htmlFor="businessName">Business name</label><input id="businessName" name="businessName" required placeholder="Your company"/></div><div className="field"><label htmlFor="firstName">Your name</label><input id="firstName" name="firstName" required placeholder="First name"/></div><div className="field"><label htmlFor="email">Work email</label><input id="email" name="email" type="email" required placeholder="you@company.com"/></div><div className="field"><label htmlFor="phone">Phone</label><input id="phone" name="phone" type="tel" placeholder="Best number"/></div><div className="field"><label htmlFor="website">Website</label><input id="website" name="website" type="url" placeholder="https://"/></div><div className="field full"><label htmlFor="industry">Industry</label><select id="industry" name="industry" required defaultValue={defaultIndustry}>{!defaultIndustry&&<option value="" disabled>Select your industry</option>}{industries.map(i=><option key={i.slug} value={i.slug}>{i.label}</option>)}<option value="other">Other</option></select></div><div className="field full"><label htmlFor="challenge">Where are leads slipping through?</label><textarea id="challenge" name="challenge" rows={3} placeholder="Missed calls, slow follow-up, no-shows, after-hours inquiries…"/></div><input type="hidden" name="sourcePath" value={typeof window!=="undefined"?window.location.pathname:"/"}/><button className="button button-primary form-submit" disabled={status==="sending"}>{status==="sending"?"Sending…":"Build my free custom demo"}<span>↗</span></button><p className="form-note">No setup fee. No obligation. We’ll only use your details to prepare and discuss your demo.</p>{status==="error"&&<p className="form-error" role="alert">Something interrupted the request. Please try once more.</p>}</form>;
}
