import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { Footer } from "../../components/footer";
import { IntakeForm } from "../../components/intake-form";
import { SiteHeader } from "../../components/site-header";
import { getIndustry, industries } from "../../lib/industries";

export function generateStaticParams(){return industries.map(i=>({slug:i.slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const i=getIndustry(slug);return i?{title:`AI Lead Conversion for ${i.label}`,description:i.intro}:{};}
export default async function IndustryPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const i=getIndustry(slug);if(!i)notFound();return <main><SiteHeader/><section className="industry-hero shell"><div><p className="eyebrow"><i/> {i.eyebrow.toUpperCase()}</p><h1 className="display">{i.headline}</h1><p className="lead">{i.intro}</p><div className="actions"><Link className="button button-primary" href="#industry-demo">Build my {i.label} demo <span>↗</span></Link><Link className="text-link" href="#playbook">See the playbook <span>→</span></Link></div></div><div className="industry-thread"><div className="thread-head"><span><i/> {i.moment}</span><small>LIVE</small></div><article className="bubble lead-bubble"><b>{i.name}</b><p>{i.message}</p></article><article className="bubble zeem-bubble"><b>Zeem agent</b><p>{i.reply}</p></article><div className="thread-outcome"><span>✓</span><div><small>OUTCOME</small><b>{i.outcome}</b></div></div></div></section><section className="industry-statement"><div className="shell"><p className="kicker">THE MOMENT THAT MATTERS</p><h2 className="display section-title">{i.pain}</h2></div></section><section id="playbook" className="section shell"><div className="section-head"><div><p className="kicker">YOUR CONVERSION PLAYBOOK</p><h2 className="display section-title">From first contact to the right <em>next step.</em></h2></div><p>We configure the agent around your actual rules, availability, tone, service area and handoff—not a generic industry script.</p></div><div className="workflow-list">{i.workflow.map((s,n)=><article key={s}><span>0{n+1}</span><h3>{s}</h3><i>↗</i></article>)}</div></section><section className="section usecase-section"><div className="shell usecase-grid"><div><p className="kicker">WHAT ZEEM CAN OWN</p><h2 className="display section-title">Repetitive work,<br/><em>handled.</em></h2><p>{i.guardrail}</p></div><div className="usecase-list">{i.useCases.map((u,n)=><div key={u}><span>0{n+1}</span><b>{u}</b><i>✓</i></div>)}</div></div></section><section id="industry-demo" className="section request-section"><div className="shell request-grid"><div><p className="kicker">BUILT AROUND YOUR BUSINESS</p><h2 className="display section-title">See your {i.label} workflow before you buy.</h2><p>Give us your website and the place leads are slipping through. We’ll prepare a custom demonstration using your services and real intake logic.</p><dl className="mini-proof"><div><dt>01</dt><dd>Your brand and services</dd></div><div><dt>02</dt><dd>Your qualification and handoff</dd></div><div><dt>03</dt><dd>Your follow-up sequence</dd></div></dl></div><IntakeForm defaultIndustry={i.slug}/></div></section><Footer/></main>}
